# Generated by Django 4.1.1 on 2022-10-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0003_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(default="This is about you fucking asshole"),
        ),
    ]
