# Generated by Django 4.1.1 on 2022-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0008_alter_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require", models.CharField(max_length=200, null=True)),
                ("start_time", models.DateField()),
                ("end_time", models.TimeField()),
            ],
        ),
    ]
